const COMPLETE_URL = 'data/chingshui-chongshe-records.json';
const COLORS = { rust:'#a9542d', rust2:'#bd592d', gold:'#dda83e', blue:'#557684', green:'#8fa05c', beige:'#c9b79d', brown:'#713b24', paper:'#f8f4ec', ink:'#39342e', muted:'#71685e', grid:'#ddd4c6' };
const NS = 'http://www.w3.org/2000/svg';
const fixed = {
  sex: [['Male / prob. male',12,COLORS.blue],['Female / prob. female',16,COLORS.rust2],['Indeterminate',25,COLORS.beige]],
  age: [['Infant (<3)',5,COLORS.green],['Child (3–12)',7,COLORS.green],['Adolescent (12–20)',4,COLORS.gold],['Young adult (20–35)',18,COLORS.rust2],['Mature adult (35–50)',17,COLORS.rust],['Older adult (50+)',2,COLORS.brown]],
  ageSex: [
    ['Infant (<3)',0,0,5],['Child (3–12)',0,0,7],['Adolescent (12–20)',0,0,4],
    ['Young adult (20–35)',4,10,4],['Mature adult (35–50)',6,6,5],['Older adult (50+)',2,0,0]
  ],
  body: [['Prone',35,COLORS.rust],['Supine',13,COLORS.blue],['Side-lying',4,COLORS.green],['Unknown',1,COLORS.beige]],
  limb: [['Extended',42,COLORS.green],['Unknown',7,COLORS.beige],['Flexed',4,COLORS.rust2]],
  layers: [['L3a',1,'upper'],['L3b',9,'upper'],['L3c',5,'upper'],['L3d',13,'lower'],['L3e',16,'lower'],['L3f',6,'lower'],['L3g',2,'lower'],['L4',1,'lower']],
  byLayer: { 'Lower cultural layer':[23,11,3,1], 'Upper cultural layer':[12,2,1,0] },
  pathology: [['Linear enamel hypoplasia',15,'oral'],['Osteophytes / bone spurs',15,'skeletal'],['Dental calculus',11,'oral'],['Vertebral pathology',9,'skeletal'],['Periodontal / abscess',7,'oral'],['Dental caries',6,'oral'],['Dental wear',5,'oral'],['Cribra orbitalia',4,'skeletal'],['Malocclusion',4,'oral'],['Arthritic change',4,'skeletal'],['Osteoporosis',1,'skeletal']],
  pathologyLayer: [
    ['Linear enamel hypoplasia',26.7,28.9],['Dental calculus',33.3,15.8],['Osteophytes / bone spurs',33.3,26.3],
    ['Vertebral pathology',20.0,15.8],['Cribra orbitalia',0,10.5],['Periodontal / abscess',13.3,13.2]
  ],
  pathologyAge: [['Infant (<3)',0],['Child (3–12)',0.7],['Adolescent (12–20)',1.2],['Young adult (20–35)',2.3],['Mature adult (35–50)',1.2],['Older adult (50+)',4.5]],
  goods: [['No recorded goods',42,COLORS.beige],['Face/head-covering pottery',4,COLORS.gold],['Pottery-lined base',4,COLORS.gold],['Pottery jar goods',3,COLORS.gold]],
  assemblage: [['Catalogued human burials',53,COLORS.rust2],['Fragmentary human remains',8,COLORS.gold],['Animal / mixed deposits',7,COLORS.green]],
  heatmap: { rows:['Female / prob. female','Male / prob. male','Indeterminate'], cols:['Prone','Supine','Side-lying','Unknown'], values:[[11,4,1,0],[7,5,0,0],[17,4,3,1]] }
};

function el(name, attrs={}, text='') { const node=document.createElementNS(NS,name); Object.entries(attrs).forEach(([k,v])=>node.setAttribute(k,v)); if(text!==undefined&&text!==null) node.textContent=text; return node; }
function svg(hostId, width=900, height=480, label='Chart') { const host=document.getElementById(hostId); host.innerHTML=''; const s=el('svg',{viewBox:`0 0 ${width} ${height}`,role:'img','aria-label':label,preserveAspectRatio:'xMidYMid meet'}); host.appendChild(s); return s; }
function text(s,x,y,value,cls='chart-label',anchor='start',extra={}) { const t=el('text',{x,y,class:cls,'text-anchor':anchor,...extra},value); s.appendChild(t); return t; }
function line(s,x1,y1,x2,y2,cls='chart-gridline',extra={}) { s.appendChild(el('line',{x1,y1,x2,y2,class:cls,...extra})); }
function rect(s,x,y,w,h,fill,extra={}) { s.appendChild(el('rect',{x,y,width:w,height:h,fill,...extra})); }
function wrapLabel(s,x,y,label,maxChars=18,anchor='end',cls='chart-label') { const words=label.split(' '); const lines=[]; let current=''; words.forEach(word=>{ if((current+' '+word).trim().length>maxChars&&current){lines.push(current);current=word;}else current=(current+' '+word).trim();}); if(current)lines.push(current); const t=el('text',{x,y,class:cls,'text-anchor':anchor}); lines.forEach((ln,i)=>t.appendChild(el('tspan',{x,dy:i===0?0:15},ln))); s.appendChild(t); return t; }
function niceMax(value) { if(value<=5)return 5; if(value<=20)return Math.ceil(value/5)*5; return Math.ceil(value/10)*10; }
function pct(n,total){return total?Math.round(n/total*100):0;}

async function loadPartitionedJson(url) { const r=await fetch(url); if(!r.ok)throw new Error(`${url}: ${r.status}`); const manifest=await r.json(); if(Array.isArray(manifest.records))return manifest.records; const base=new URL(url,location.href); const parts=await Promise.all((manifest.parts||[]).map(p=>fetch(new URL(p,base)).then(x=>{if(!x.ok)throw new Error(`${p}: ${x.status}`);return x.json();}))); return parts.flatMap(p=>p.records||[]); }

function parseAzimuth(value){ if(!value)return null; const raw=String(value).toUpperCase().replace(/\s/g,''); if(/UNKNOWN|不詳|^X$/.test(raw))return null; const n=Number(raw.match(/\d+(?:\.\d+)?/)?.[0]); if(!Number.isFinite(n)){ const cardinal={N:0,E:90,S:180,W:270}; return cardinal[raw]??null; } const letters=raw.match(/[NESW]/g)||[]; if(letters.length<2)return null; const [a,b]=letters; const base={N:0,E:90,S:180,W:270}[a]; const sign={NE:1,NW:-1,EN:-1,ES:1,SE:-1,SW:1,WS:-1,WN:1}[a+b]; return ((base+sign*n)%360+360)%360; }
function circularMean(values){ if(!values.length)return null; const x=values.reduce((a,d)=>a+Math.cos(d*Math.PI/180),0); const y=values.reduce((a,d)=>a+Math.sin(d*Math.PI/180),0); return (Math.atan2(y,x)*180/Math.PI+360)%360; }
function orientationData(records){ return records.map(r=>({id:r.id,layer:r.cultural_layer_en,az:parseAzimuth(r.head_direction)})).filter(d=>Number.isFinite(d.az)); }

function verticalBars(hostId,data,{label='Bar chart',max=null,percent=false,height=470,rotate=true}={}){ const s=svg(hostId,900,height,label), m={l:72,r:24,t:24,b:rotate?115:75}, W=900-m.l-m.r,H=height-m.t-m.b, yMax=max||niceMax(Math.max(...data.map(d=>d[1]))), step=W/data.length, bw=step*.72; for(let i=0;i<=5;i++){const v=yMax*i/5,y=m.t+H-(v/yMax)*H;line(s,m.l,y,900-m.r,y);text(s,m.l-10,y+4,percent?`${Math.round(v)}%`:String(Math.round(v*10)/10),'chart-label','end');} line(s,m.l,m.t+H,900-m.r,m.t+H,'chart-axis'); data.forEach((d,i)=>{const x=m.l+i*step+(step-bw)/2,h=d[1]/yMax*H,y=m.t+H-h;rect(s,x,y,bw,h,d[2]||COLORS.rust,{rx:2});text(s,x+bw/2,y-8,percent?`${d[1]}%`:String(d[1]),'chart-value','middle'); const tx=x+bw/2,ty=m.t+H+22; text(s,tx,ty,d[0],'chart-label',rotate?'end':'middle',rotate?{transform:`rotate(-25 ${tx} ${ty})`}:{ });}); return s; }
function horizontalBars(hostId,data,{label='Horizontal bar chart',height=520,max=null,showPercent=false,total=53,left=245}={}){ const s=svg(hostId,900,height,label),m={l:left,r:85,t:20,b:45},W=900-m.l-m.r,H=height-m.t-m.b,yMax=max||niceMax(Math.max(...data.map(d=>d[1]))),step=H/data.length,bh=step*.68; for(let i=0;i<=5;i++){const v=yMax*i/5,x=m.l+v/yMax*W;line(s,x,m.t,x,m.t+H);text(s,x,m.t+H+22,String(Math.round(v*10)/10),'chart-label','middle');} data.forEach((d,i)=>{const y=m.t+i*step+(step-bh)/2,w=d[1]/yMax*W;rect(s,m.l,y,w,bh,d[2]||COLORS.gold,{rx:1});wrapLabel(s,m.l-10,y+bh/2+4,d[0],28,'end');text(s,m.l+w+10,y+bh/2+4,showPercent?`${d[1]} (${pct(d[1],total)}%)`:String(d[1]),'chart-value');}); return s; }
function donut(hostId,data,{label='Donut chart',height=500}={}){ const s=svg(hostId,900,height,label),cx=365,cy=height/2,r=155,inner=88,total=data.reduce((a,d)=>a+d[1],0); let a=-Math.PI/2; data.forEach((d,i)=>{const span=d[1]/total*Math.PI*2,a2=a+span; const p=(rr,ang)=>[cx+rr*Math.cos(ang),cy+rr*Math.sin(ang)]; const [x1,y1]=p(r,a),[x2,y2]=p(r,a2),[ix2,iy2]=p(inner,a2),[ix1,iy1]=p(inner,a); const path=`M${x1},${y1} A${r},${r} 0 ${span>Math.PI?1:0} 1 ${x2},${y2} L${ix2},${iy2} A${inner},${inner} 0 ${span>Math.PI?1:0} 0 ${ix1},${iy1} Z`;s.appendChild(el('path',{d:path,fill:d[2],stroke:COLORS.paper,'stroke-width':5})); const mid=a+span/2,[tx,ty]=p((r+inner)/2,mid);text(s,tx,ty-4,`${pct(d[1],total)}%`,'chart-value','middle',{fill:'#fff'});text(s,tx,ty+14,`(${d[1]})`,'chart-value','middle',{fill:'#fff'}); const ly=140+i*82;rect(s,610,ly-15,22,22,d[2],{rx:2});text(s,646,ly,d[0],'chart-legend');a=a2;});text(s,cx,cy-3,String(total),'chart-value','middle',{'font-size':36});text(s,cx,cy+33,'burials','chart-value','middle',{'font-size':24});return s; }
function stackedBars(hostId,groups,series,{label='Stacked bar chart',height=500}={}){ const s=svg(hostId,900,height,label),m={l:80,r:30,t:35,b:95},W=900-m.l-m.r,H=height-m.t-m.b, totals=groups.map(g=>g.values.reduce((a,b)=>a+b,0)),max=niceMax(Math.max(...totals)),step=W/groups.length,bw=step*.55;for(let i=0;i<=5;i++){const v=max*i/5,y=m.t+H-v/max*H;line(s,m.l,y,900-m.r,y);text(s,m.l-10,y+4,String(Math.round(v)),'chart-label','end');}groups.forEach((g,i)=>{let y=m.t+H;g.values.forEach((v,j)=>{const h=v/max*H;y-=h;rect(s,m.l+i*step+(step-bw)/2,y,bw,h,series[j].color,{stroke:COLORS.paper,'stroke-width':2});if(v)text(s,m.l+i*step+step/2,y+h/2+4,String(v),'chart-value','middle',{fill:'#fff'});});wrapLabel(s,m.l+i*step+step/2,m.t+H+25,g.label,23,'middle');});series.forEach((sr,i)=>{const x=260+i*155,y=height-22;rect(s,x,y-13,22,13,sr.color);text(s,x+30,y,sr.label,'chart-legend');});return s;}
function groupedBars(hostId,data,{label='Grouped bar chart',height=500}={}){const s=svg(hostId,900,height,label),m={l:70,r:30,t:30,b:125},W=900-m.l-m.r,H=height-m.t-m.b,max=35,step=W/data.length,bw=step*.34;for(let i=0;i<=7;i++){const v=i*5,y=m.t+H-v/max*H;line(s,m.l,y,900-m.r,y);text(s,m.l-8,y+4,String(v),'chart-label','end');}data.forEach((d,i)=>{const x=m.l+i*step+step*.13;[[d[1],COLORS.gold],[d[2],COLORS.rust]].forEach((a,j)=>{const h=a[0]/max*H;rect(s,x+j*bw,m.t+H-h,bw-3,h,a[1]);});wrapLabel(s,m.l+i*step+step/2,m.t+H+24,d[0],14,'middle');});rect(s,650,25,22,13,COLORS.gold);text(s,680,37,'Upper layer (n=15)','chart-legend');rect(s,650,48,22,13,COLORS.rust);text(s,680,60,'Lower layer (n=38)','chart-legend');return s;}
function lineChart(hostId,data,{label='Line chart',height=500,max=5}={}){const s=svg(hostId,900,height,label),m={l:70,r:35,t:30,b:110},W=900-m.l-m.r,H=height-m.t-m.b,step=W/(data.length-1);for(let i=0;i<=max;i++){const y=m.t+H-i/max*H;line(s,m.l,y,900-m.r,y);text(s,m.l-10,y+4,String(i),'chart-label','end');}const pts=data.map((d,i)=>[m.l+i*step,m.t+H-d[1]/max*H]);const area=`M${pts[0][0]},${m.t+H} `+pts.map(p=>`L${p[0]},${p[1]}`).join(' ')+` L${pts.at(-1)[0]},${m.t+H} Z`;s.appendChild(el('path',{d:area,fill:COLORS.rust,opacity:.12}));s.appendChild(el('polyline',{points:pts.map(p=>p.join(',')).join(' '),fill:'none',stroke:COLORS.rust2,'stroke-width':4}));pts.forEach((p,i)=>{s.appendChild(el('circle',{cx:p[0],cy:p[1],r:8,fill:COLORS.gold,stroke:COLORS.rust2,'stroke-width':2}));text(s,p[0],p[1]-14,data[i][1].toFixed(1),'chart-value','middle');const tx=p[0],ty=m.t+H+25;text(s,tx,ty,data[i][0],'chart-label','end',{transform:`rotate(-24 ${tx} ${ty})`});});return s;}
function heatmap(hostId,model){const s=svg(hostId,900,500,'Sex by body position heatmap'),m={l:225,r:100,t:35,b:75},W=900-m.l-m.r,H=500-m.t-m.b,cw=W/model.cols.length,ch=H/model.rows.length,max=Math.max(...model.values.flat());model.cols.forEach((c,i)=>text(s,m.l+i*cw+cw/2,m.t+H+30,c,'chart-label','middle'));model.rows.forEach((r,i)=>text(s,m.l-12,m.t+i*ch+ch/2+5,r,'chart-label','end'));model.values.forEach((row,i)=>row.forEach((v,j)=>{const ratio=v/max;const hue=35-20*ratio,light=96-64*ratio;rect(s,m.l+j*cw,m.t+i*ch,cw,ch,`hsl(${hue} 90% ${light}%)`,{stroke:COLORS.paper,'stroke-width':2});text(s,m.l+j*cw+cw/2,m.t+i*ch+ch/2+6,String(v),'chart-value','middle',{fill:ratio>.58?'#fff':COLORS.ink,'font-size':20});}));return s;}
function pyramid(hostId,data){const s=svg(hostId,900,550,'Age by sex structure'),m={l:220,r:35,t:25,b:55},W=900-m.l-m.r,H=550-m.t-m.b,center=m.l+W*.38,unit=(W*.55)/15,step=H/data.length,bh=step*.78;for(let v=-7;v<=15;v+=2){const x=center+v*unit;line(s,x,m.t,x,m.t+H);text(s,x,m.t+H+24,String(Math.abs(v)),'chart-label','middle');}line(s,center,m.t,center,m.t+H,'chart-axis');data.forEach((d,i)=>{const y=m.t+(data.length-1-i)*step+(step-bh)/2;wrapLabel(s,m.l-12,y+bh/2+4,d[0],24,'end');rect(s,center-d[1]*unit,y,d[1]*unit,bh,COLORS.blue);rect(s,center,y,d[2]*unit,bh,COLORS.rust2);rect(s,center+d[2]*unit,y,d[3]*unit,bh,COLORS.beige);});text(s,center-110,540,'← Male','chart-legend','middle');text(s,center+220,540,'Female / indeterminate →','chart-legend','middle');return s;}
function polar(hostId,azimuths,{height=570,compact=false}={}){const s=svg(hostId,compact?520:760,height,'Polar histogram of burial head orientation'),cx=compact?255:380,cy=compact?290:300,R=compact?185:225,bin=15,bins=Array(360/bin).fill(0);azimuths.forEach(a=>bins[Math.floor(((a%360)+360)%360/bin)]++);const max=Math.max(...bins,1),rings=compact?4:8;for(let i=1;i<=rings;i++){const r=R*i/rings;s.appendChild(el('circle',{cx,cy,r,fill:'none',stroke:'#aeb2b3','stroke-width':1}));if(!compact)text(s,cx-7,cy-r+4,String(Math.round(max*i/rings)),'chart-label','end');}for(let d=0;d<360;d+=45){const a=(d-90)*Math.PI/180;line(s,cx,cy,cx+R*Math.cos(a),cy+R*Math.sin(a),'chart-gridline');const labels={0:'N',45:'NE',90:'E',135:'SE',180:'S',225:'SW',270:'W',315:'NW'};text(s,cx+(R+26)*Math.cos(a),cy+(R+26)*Math.sin(a)+5,labels[d],'chart-value','middle');}bins.forEach((v,i)=>{if(!v)return;const a1=(i*bin-90)*Math.PI/180,a2=((i+1)*bin-90)*Math.PI/180,r=R*v/max;const p=(rr,a)=>[cx+rr*Math.cos(a),cy+rr*Math.sin(a)],[x1,y1]=p(r,a1),[x2,y2]=p(r,a2);const path=`M${cx},${cy} L${x1},${y1} A${r},${r} 0 0 1 ${x2},${y2} Z`;s.appendChild(el('path',{d:path,fill:COLORS.rust2,opacity:.9,stroke:COLORS.paper,'stroke-width':2}));});return s;}
function orientationScatter(hostId,items){const s=svg(hostId,1000,510,'Head orientation by cultural layer'),m={l:95,r:35,t:45,b:65},W=1000-m.l-m.r,H=510-m.t-m.b,rows={'Upper cultural layer':m.t+70,'Lower cultural layer':m.t+H-70};for(let x=50;x<=300;x+=50){const px=m.l+(x-60)/(260)*W;line(s,px,m.t,px,m.t+H);text(s,px,m.t+H+24,String(x),'chart-label','middle');}Object.entries(rows).forEach(([k,y])=>text(s,m.l-15,y+5,k.startsWith('Upper')?'Upper':'Lower','chart-value','end'));const jitter={};items.forEach((d)=>{const y0=rows[d.layer]??rows['Lower cultural layer'];const key=`${d.layer}-${Math.round(d.az/4)}`;jitter[key]=(jitter[key]||0)+1;const offset=(jitter[key]-1)*9-9;const x=m.l+(d.az-60)/260*W,y=y0+offset; s.appendChild(el('circle',{cx:x,cy:y,r:8,fill:d.layer?.startsWith('Upper')?COLORS.gold:COLORS.rust,stroke:COLORS.brown,'stroke-width':1,opacity:.9}));if(d.az>250){line(s,x-70,y-100,x-5,y-10,'chart-axis',{stroke:COLORS.blue});text(s,x-72,y-108,'single reversed burial','chart-label','middle',{fill:COLORS.blue});}});['Upper cultural layer','Lower cultural layer'].forEach((layer,idx)=>{const vals=items.filter(d=>d.layer===layer).map(d=>d.az),mean=circularMean(vals),x=m.l+(mean-60)/260*W;line(s,x,m.t,x,m.t+H,'chart-axis',{stroke:idx?COLORS.rust:COLORS.gold,'stroke-width':3,'stroke-dasharray':'8 6'});text(s,x,idx?500:28,`mean ${Math.round(mean)}°`,'chart-value','middle',{fill:idx?COLORS.rust:COLORS.gold});});text(s,550,505,'Head azimuth (compass bearing, °) — 90°=E, 180°=S, 270°=W','chart-legend','middle');return s;}
function faunal(hostId){const s=svg(hostId,1000,470,'Faunal reassessment and human bone commingling');const taxa=[['Dog',2,COLORS.rust],['Cervid (deer)',2,COLORS.green],['Small mammal',2,COLORS.gold],['Pig',1,COLORS.blue]],m={l:70,r:520,t:65,b:75},W=1000-m.l-m.r,H=470-m.t-m.b,max=2.1,step=W/taxa.length,bw=step*.62;taxa.forEach((d,i)=>{const x=m.l+i*step+(step-bw)/2,h=d[1]/max*H,y=m.t+H-h;rect(s,x,y,bw,h,d[2]);text(s,x+bw/2,y-10,String(d[1]),'chart-value','middle');const tx=x+bw/2,ty=m.t+H+25;text(s,tx,ty,d[0],'chart-label','end',{transform:`rotate(-24 ${tx} ${ty})`});});text(s,m.l,m.t-20,'Re-identified taxa in animal/mixed deposits','chart-title');const cx=790,cy=245,r=120,total=7,a1=3/7*Math.PI*2-Math.PI/2;const path1=`M${cx},${cy} L${cx},${cy-r} A${r},${r} 0 0 1 ${cx+r*Math.cos(a1)},${cy+r*Math.sin(a1)} Z`;s.appendChild(el('path',{d:path1,fill:COLORS.rust2,stroke:COLORS.paper,'stroke-width':4}));const path2=`M${cx},${cy} L${cx+r*Math.cos(a1)},${cy+r*Math.sin(a1)} A${r},${r} 0 1 1 ${cx},${cy-r} Z`;s.appendChild(el('path',{d:path2,fill:COLORS.beige,stroke:COLORS.paper,'stroke-width':4}));text(s,770,230,'3','chart-value','middle',{'font-size':20});text(s,835,270,'4','chart-value','middle',{'font-size':20});text(s,790,85,'Commingling of human bone','chart-title','middle');text(s,640,205,'Contains','chart-value','end');text(s,640,223,'human bone','chart-value','end');text(s,927,255,'Purely faunal /','chart-value');text(s,927,273,'unidentified','chart-value');return s;}

function render(records){const orientations=orientationData(records),mean=circularMean(orientations.map(d=>d.az));document.getElementById('profileKpis').innerHTML=[['53','catalogued burials'],['68','total records (incl. fragmentary)'],['66%','buried prone (face-down)'],[`~${Math.round(mean||115)}°`,'mean head azimuth (ESE)'],['70%','show ≥1 pathology']].map(([v,l])=>`<div class="profile-kpi"><strong>${v}</strong><span>${l}</span></div>`).join('');
  polar('profileOrientation',orientations.map(d=>d.az),{height:380,compact:true}); verticalBars('profileBody',fixed.body,{height:350,rotate:true,max:40}); verticalBars('profileAge',fixed.age,{height:350,rotate:true,max:20}); horizontalBars('profilePathology',fixed.pathology.slice(0,6).map(d=>[d[0],d[1],COLORS.gold]),{height:320,left:180,max:16});
  polar('orientationRose',orientations.map(d=>d.az),{height:650}); orientationScatter('orientationLayer',orientations); document.getElementById('orientationCaption').textContent=`n=${orientations.length} burials with recorded direction; circular mean ≈${Math.round(mean)}°.`;
  donut('sexDonut',fixed.sex); verticalBars('ageDistribution',fixed.age,{height:480,max:20}); pyramid('ageSexPyramid',fixed.ageSex);
  verticalBars('bodyPosition',fixed.body,{height:480,max:40}); verticalBars('limbPosition',fixed.limb,{height:480,max:45}); heatmap('sexBodyHeatmap',fixed.heatmap); horizontalBars('graveGoods',fixed.goods,{height:450,left:245,max:45});
  horizontalBars('stratigraphyChart',fixed.layers.map(d=>[d[0],d[1],d[2]==='upper'?COLORS.gold:COLORS.rust]),{height:600,left:90,max:17}); stackedBars('positionLayer',Object.entries(fixed.byLayer).map(([label,values])=>({label,values})),[{label:'Prone',color:COLORS.rust},{label:'Supine',color:COLORS.blue},{label:'Side-lying',color:COLORS.green},{label:'Unknown',color:COLORS.beige}],{height:500});
  horizontalBars('pathologyPrevalence',fixed.pathology.map(d=>[d[0],d[1],d[2]==='oral'?COLORS.gold:COLORS.blue]),{height:650,left:255,max:18,showPercent:true}); groupedBars('pathologyLayer',fixed.pathologyLayer,{height:510}); lineChart('pathologyAge',fixed.pathologyAge,{height:500,max:5});
  verticalBars('assemblageComposition',fixed.assemblage,{height:470,max:55,rotate:false}); faunal('faunalReassessment');
}

(async()=>{try{const records=await loadPartitionedJson(COMPLETE_URL);render(records);document.getElementById('visualStatus').textContent=`Loaded ${records.length} complete burial records.`;}catch(error){console.error(error);document.getElementById('visualStatus').textContent='Visuals could not load the dataset. Open through a web server or GitHub Pages.';}})();
